channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.3.3
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
